version: '3'
services:
  gestionutilisateurs:
    image: gestionutilisateurs
    ports:
      - 8081:8081
  gestionalertes:
    image: gestionalertes
    ports:
      - 8000:8000
  fournisseursalertes:
    image: fournisseursalertes
    ports:
      - 8001:8001
  projet:
    image: project
    ports:
      - 3000:3000


